export type DeployedContracts = Record<number, Record<string, { address: `0x${string}`; abi: any[] }>>;

// Auto-generated by scripts/generateDeployedContracts.ts
export const deployedContracts: DeployedContracts = {} as const;
