import { promises as fs } from "fs";
import path from "path";

type Deployment = { address: `0x${string}`; abi: any[] };

const root = path.resolve(__dirname, "../../..");
const deploymentsRoot = path.join(root, "deployments");
const outputFile = path.join(__dirname, "../contracts/deployedContracts.ts");

const loadChainId = async (networkDir: string): Promise<number> => {
  const chainIdFile = path.join(networkDir, ".chainId");
  const value = await fs.readFile(chainIdFile, "utf8");
  return Number(value.trim());
};

const run = async () => {
  const result: Record<number, Record<string, Deployment>> = {};
  const networks = await fs.readdir(deploymentsRoot);

  for (const network of networks) {
    const networkDir = path.join(deploymentsRoot, network);
    const stat = await fs.stat(networkDir);
    if (!stat.isDirectory()) continue;

    const chainId = await loadChainId(networkDir);
    result[chainId] = {};

    const files = await fs.readdir(networkDir);
    for (const file of files) {
      if (!file.endsWith(".json") || file === ".chainId") continue;
      if (file === "solcInputs") continue;
      const fullPath = path.join(networkDir, file);
      const fileStat = await fs.stat(fullPath);
      if (!fileStat.isFile()) continue;

      const content = JSON.parse(await fs.readFile(fullPath, "utf8"));
      if (!content.address || !content.abi) continue;

      const name = file.replace(".json", "");
      result[chainId][name] = {
        address: content.address,
        abi: content.abi,
      };
    }
  }

  const body = `export type DeployedContracts = Record<number, Record<string, { address: \`0x\${string}\`; abi: any[] }>>;\n\n// Auto-generated by scripts/generateDeployedContracts.ts\nexport const deployedContracts: DeployedContracts = ${JSON.stringify(
    result,
    null,
    2,
  )} as const;\n`;

  await fs.writeFile(outputFile, body, "utf8");
  console.log(`Wrote ${outputFile}`);
};

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
